# Build settings
gems:
  - jekyll-paginate
  - github-pages

# Site settings
title: "uuutee.log"
description: > # this means to ignore newlines until "email:"
   WEB DEVELOPMENT NOTE

email: uuuteenet@gmail.com
logo: "/assets/images/logo.png"
cover: "/assets/images/mainimg.jpg"

name: 'uuutee'
author: 'uuutee'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://uuutee.github.io/" # the base hostname & protocol for your site
baseurl: ""
twitter_handle: '@uuutee'

# social icons and sharing options
social:
  - icon: github
    url:  https://github.com/uuutee
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/uuutee
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

# category archive
collections:
  my_categories:
    output: true
    permalink: /category/:name/

# table of contents
minItemsToShowToc: 1 # 目次の項目を表示する最小数 
tocTopTag: h2 # 目次の項目となる見出しの要素。h1〜h5まで指定可能。
anchorPrefix: tocAnchor- # 見出し要素のID属性に付与する接頭辞
showToggleButton: false # トグルボタンの表示非表示